services:
  postgres:
    build:
      context: .
      dockerfile: TestDb.Containerfile
    ports:
      # Mapping port 9876 on the host to port 5432 on the container for PostgreSQL to avoid conflicts with other local postgresql instances
      - "9876:5432"
    environment:
      POSTGRES_USER: glvd
      POSTGRES_DB: glvd
      POSTGRES_PASSWORD: glvd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U glvd -d glvd"]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 10s
